import {
  parsePackageBlueprint,
  type PackageBlueprint,
  type PackageBlueprintMember,
} from "./package-blueprint";

const observedAt = "2026-07-21";

type SourceEvidence = Omit<PackageBlueprintMember, "position" | "defaultSelected" | "rationale">;

const sources = {
  vercelReactBestPractices: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "vercel-labs",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/vercel-labs/agent-skills",
      skillPath: "skills/react-best-practices/SKILL.md",
      upstreamSkillName: "vercel-react-best-practices",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "skills/react-best-practices/SKILL.md",
    },
    observedSource: {
      headSha: "f8a72b9603728bb92a217a879b7e62e43ad76c81",
      observedAt,
    },
  },
  vercelCompositionPatterns: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "vercel-labs",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/vercel-labs/agent-skills",
      skillPath: "skills/composition-patterns/SKILL.md",
      upstreamSkillName: "vercel-composition-patterns",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "skills/composition-patterns/SKILL.md",
    },
    observedSource: {
      headSha: "f8a72b9603728bb92a217a879b7e62e43ad76c81",
      observedAt,
    },
  },
  shadcn: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "shadcn-ui",
      repository: "ui",
      repositoryUrl: "https://github.com/shadcn-ui/ui",
      skillPath: "skills/shadcn/SKILL.md",
      upstreamSkillName: "shadcn",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE.md",
    },
    observedSource: {
      headSha: "20442886c5cfb440441c35030462fbdf64838655",
      observedAt,
    },
  },
  anthropicFrontendDesign: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/frontend-design/SKILL.md",
      upstreamSkillName: "frontend-design",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/frontend-design/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  impeccable: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "pbakaus",
      repository: "impeccable",
      repositoryUrl: "https://github.com/pbakaus/impeccable",
      skillPath: ".agents/skills/impeccable/SKILL.md",
      upstreamSkillName: "impeccable",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "58044860fb613595ce493c388ce3571b20140f9d",
      observedAt,
    },
  },
  gsapScrolltrigger: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/gsap-scrolltrigger/SKILL.md",
      upstreamSkillName: "gsap-scrolltrigger",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  threejsWebgl: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/threejs-webgl/SKILL.md",
      upstreamSkillName: "threejs-webgl",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  reactThreeFiber: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/react-three-fiber/SKILL.md",
      upstreamSkillName: "react-three-fiber",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  motionFramer: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/motion-framer/SKILL.md",
      upstreamSkillName: "motion-framer",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  web3dIntegrationPatterns: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/web3d-integration-patterns/SKILL.md",
      upstreamSkillName: "web3d-integration-patterns",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  hyperframesAnimation: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "heygen-com",
      repository: "hyperframes",
      repositoryUrl: "https://github.com/heygen-com/hyperframes",
      skillPath: "skills/hyperframes-animation/SKILL.md",
      upstreamSkillName: "hyperframes-animation",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "32c41ea7dca14cfa6aa781335ccdd7870e52ceb4",
      observedAt,
    },
  },
  wrangler: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/wrangler/SKILL.md",
      upstreamSkillName: "wrangler",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  workersBestPractices: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/workers-best-practices/SKILL.md",
      upstreamSkillName: "workers-best-practices",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  azureDeploy: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "azure-skills",
      repositoryUrl: "https://github.com/microsoft/azure-skills",
      skillPath: "skills/azure-deploy/SKILL.md",
      upstreamSkillName: "azure-deploy",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d3e702378432d4d53ca80b2bba0fbb4af83ace24",
      observedAt,
    },
  },
  easHosting: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/eas-hosting/SKILL.md",
      upstreamSkillName: "eas-hosting",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  easAppStores: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/eas-app-stores/SKILL.md",
      upstreamSkillName: "eas-app-stores",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  securityAudit: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "security-audit-skill",
      repositoryUrl: "https://github.com/cloudflare/security-audit-skill",
      skillPath: "skills/security-audit/SKILL.md",
      upstreamSkillName: "security-audit",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bac42001ddd90a4dcd8d5a5045199283a8eba75",
      observedAt,
    },
  },
  firebaseSecurityRulesAuditor: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-security-rules-auditor/SKILL.md",
      upstreamSkillName: "firebase-security-rules-auditor",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt,
    },
  },
  azureCompliance: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "azure-skills",
      repositoryUrl: "https://github.com/microsoft/azure-skills",
      skillPath: "skills/azure-compliance/SKILL.md",
      upstreamSkillName: "azure-compliance",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d3e702378432d4d53ca80b2bba0fbb4af83ace24",
      observedAt,
    },
  },
  turnstileSpin: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/turnstile-spin/SKILL.md",
      upstreamSkillName: "turnstile-spin",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  cloudflareOne: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/cloudflare-one/SKILL.md",
      upstreamSkillName: "cloudflare-one",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  expoProjectStructure: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-project-structure/SKILL.md",
      upstreamSkillName: "expo-project-structure",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  expoRouter: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-router/SKILL.md",
      upstreamSkillName: "expo-router",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  expoDataFetching: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-data-fetching/SKILL.md",
      upstreamSkillName: "expo-data-fetching",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  expoNativeUi: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-native-ui/SKILL.md",
      upstreamSkillName: "expo-native-ui",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  expoTailwindSetup: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-tailwind-setup/SKILL.md",
      upstreamSkillName: "expo-tailwind-setup",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  expoUpgrade: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-upgrade/SKILL.md",
      upstreamSkillName: "expo-upgrade",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bd359f8a44d2446de12f1fe6e6316daf043056e",
      observedAt,
    },
  },
  supabasePostgresBestPractices: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "supabase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/supabase/agent-skills",
      skillPath: "skills/supabase-postgres-best-practices/SKILL.md",
      upstreamSkillName: "supabase-postgres-best-practices",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1ad9aaeb49caafd9e95c0a91116f71890eebbc53",
      observedAt,
    },
  },
  neonPostgres: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "neondatabase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/neondatabase/agent-skills",
      skillPath: "skills/neon-postgres/SKILL.md",
      upstreamSkillName: "neon-postgres",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d232c83a87bd61bacb1ad60de128fcc91a9b6418",
      observedAt,
    },
  },
  firebaseDataConnectBasics: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-data-connect-basics/SKILL.md",
      upstreamSkillName: "firebase-data-connect",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt,
    },
  },
  firebaseAiLogicBasics: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-ai-logic-basics/SKILL.md",
      upstreamSkillName: "firebase-ai-logic-basics",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt,
    },
  },
  huggingfaceDatasets: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "huggingface",
      repository: "skills",
      repositoryUrl: "https://github.com/huggingface/skills",
      skillPath: "skills/huggingface-datasets/SKILL.md",
      upstreamSkillName: "huggingface-datasets",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "86cdeee824b73e504198b6005bb113552cdfa7ba",
      observedAt,
    },
  },
  huggingfaceLlmTrainer: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "huggingface",
      repository: "skills",
      repositoryUrl: "https://github.com/huggingface/skills",
      skillPath: "skills/huggingface-llm-trainer/SKILL.md",
      upstreamSkillName: "huggingface-llm-trainer",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "86cdeee824b73e504198b6005bb113552cdfa7ba",
      observedAt,
    },
  },
  anthropicSkillCreator: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/skill-creator/SKILL.md",
      upstreamSkillName: "skill-creator",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/skill-creator/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  anthropicMcpBuilder: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/mcp-builder/SKILL.md",
      upstreamSkillName: "mcp-builder",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/mcp-builder/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  agentsSdk: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/agents-sdk/SKILL.md",
      upstreamSkillName: "agents-sdk",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  durableObjects: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/durable-objects/SKILL.md",
      upstreamSkillName: "durable-objects",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  sandboxSdk: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/sandbox-sdk/SKILL.md",
      upstreamSkillName: "sandbox-sdk",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
  agentBrowser: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "vercel-labs",
      repository: "agent-browser",
      repositoryUrl: "https://github.com/vercel-labs/agent-browser",
      skillPath: "skills/agent-browser/SKILL.md",
      upstreamSkillName: "agent-browser",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "81c336c1c20b80ac648e0416a7b6e0c0ae7878bb",
      observedAt,
    },
  },
  playwrightCli: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "playwright-cli",
      repositoryUrl: "https://github.com/microsoft/playwright-cli",
      skillPath: "skills/playwright-cli/SKILL.md",
      upstreamSkillName: "playwright-cli",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "eee5a185c98e6b04d88f580d45a854e9692ab50b",
      observedAt,
    },
  },
  anthropicWebappTesting: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/webapp-testing/SKILL.md",
      upstreamSkillName: "webapp-testing",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/webapp-testing/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  testDrivenDevelopment: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/test-driven-development/SKILL.md",
      upstreamSkillName: "test-driven-development",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt,
    },
  },
  systematicDebugging: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/systematic-debugging/SKILL.md",
      upstreamSkillName: "systematic-debugging",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt,
    },
  },
  verificationBeforeCompletion: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/verification-before-completion/SKILL.md",
      upstreamSkillName: "verification-before-completion",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt,
    },
  },
  requestingCodeReview: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/requesting-code-review/SKILL.md",
      upstreamSkillName: "requesting-code-review",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt,
    },
  },
  webPerf: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/web-perf/SKILL.md",
      upstreamSkillName: "web-perf",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt,
    },
  },
} as const satisfies Record<string, SourceEvidence>;

type SourceKey = keyof typeof sources;

function member(position: number, source: SourceKey, rationale: string): PackageBlueprintMember {
  return {
    position,
    defaultSelected: true,
    rationale,
    ...sources[source],
  };
}

const blueprintInputs = [
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "frontend-foundations",
    editorial: {
      title: "Frontend Foundations",
      summary: "A disciplined React and interface stack spanning architecture, performance, components, and visual craft.",
      outcome: "Ship maintainable, fast product interfaces with stronger composition and a sharper design review loop.",
      audience: ["Frontend engineers", "Product engineers", "Design engineers"],
      category: "frontend",
      tags: ["react", "nextjs", "components", "ui-design"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "brackets", colorToken: "iris" },
    },
    members: [
      member(1, "vercelReactBestPractices", "Sets a performance-aware baseline for writing and reviewing production React and Next.js code."),
      member(2, "vercelCompositionPatterns", "Adds scalable React composition techniques for resilient component APIs and design systems."),
      member(3, "shadcn", "Brings first-party shadcn guidance for selecting, integrating, and adapting accessible UI components."),
      member(4, "anthropicFrontendDesign", "Strengthens visual direction and implementation quality beyond generic application scaffolds."),
      member(5, "impeccable", "Provides an author-maintained interface critique and refinement workflow for the final quality pass."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "motion-and-3d",
    editorial: {
      title: "Motion & 3D",
      summary: "A community-led motion toolkit for scroll choreography, WebGL scenes, React 3D, and cinematic timelines.",
      outcome: "Build expressive, performant web experiences while choosing the right animation and 3D abstraction for each scene.",
      audience: ["Creative developers", "Design engineers", "Interactive studios"],
      category: "motion-3d",
      tags: ["gsap", "threejs", "webgl", "animation"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "orbit", colorToken: "magenta" },
    },
    members: [
      member(1, "gsapScrolltrigger", "Covers practical GSAP ScrollTrigger choreography for scroll-driven product and editorial sequences."),
      member(2, "threejsWebgl", "Supplies direct Three.js and WebGL patterns when scene-level control matters more than abstraction."),
      member(3, "reactThreeFiber", "Connects declarative React workflows to Three.js for componentized interactive scenes."),
      member(4, "motionFramer", "Adds focused Motion guidance for interface transitions, gestures, and layout animation."),
      member(5, "web3dIntegrationPatterns", "Explains how the included motion and 3D tools work together in one coherent application architecture."),
      member(6, "hyperframesAnimation", "Adds an Apache-licensed, author-maintained animation system for structured cinematic timelines."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "deployment",
    editorial: {
      title: "Deployment Control Plane",
      summary: "A practical release stack across Cloudflare, Azure, Expo hosting, and mobile store delivery.",
      outcome: "Move applications from local builds to production infrastructure with platform-specific operational guidance.",
      audience: ["Platform engineers", "Full-stack teams", "Mobile release owners"],
      category: "deployment",
      tags: ["cloudflare", "azure", "expo", "release"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "rocket", colorToken: "amber" },
    },
    members: [
      member(1, "wrangler", "Provides first-party Wrangler commands and workflows for Cloudflare development and deployment."),
      member(2, "workersBestPractices", "Adds production-focused Workers architecture and review guidance before a release reaches users."),
      member(3, "azureDeploy", "Covers the Azure deployment path for teams operating beyond a single infrastructure provider."),
      member(4, "easHosting", "Handles Expo web exports and Router API deployments through the supported EAS hosting workflow."),
      member(5, "easAppStores", "Completes the mobile release path with official EAS build and app-store submission guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "cybersecurity",
    editorial: {
      title: "Security Surface",
      summary: "A defensive review kit for application code, cloud posture, identity boundaries, rules, and bot protection.",
      outcome: "Catch common security weaknesses earlier and apply provider-specific controls with explicit scope and provenance.",
      audience: ["Security engineers", "Platform teams", "Application maintainers"],
      category: "cybersecurity",
      tags: ["security", "compliance", "zero-trust", "appsec"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "shield", colorToken: "emerald" },
    },
    members: [
      member(1, "securityAudit", "Provides Cloudflare's dedicated application security audit workflow for structured defensive reviews."),
      member(2, "firebaseSecurityRulesAuditor", "Checks Firebase rules with first-party product context that generic security guidance cannot supply."),
      member(3, "azureCompliance", "Adds Microsoft-authored Azure compliance assessment and remediation guidance."),
      member(4, "turnstileSpin", "Covers bot protection setup end to end, including server verification and operational checks."),
      member(5, "cloudflareOne", "Expands the package to Zero Trust access, network, data, and device policy boundaries."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "mobile",
    editorial: {
      title: "Expo Mobile Workshop",
      summary: "An official Expo foundation for project structure, routing, data, native UI, styling, and upgrades.",
      outcome: "Build and maintain production Expo applications with coherent conventions across the full development lifecycle.",
      audience: ["React Native engineers", "Expo teams", "Web-to-mobile developers"],
      category: "mobile",
      tags: ["expo", "react-native", "routing", "native-ui"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "device-mobile", colorToken: "coral" },
    },
    members: [
      member(1, "expoProjectStructure", "Establishes a durable first-party folder and project structure before application complexity grows."),
      member(2, "expoRouter", "Covers the official routing model, file conventions, layouts, groups, and navigation boundaries."),
      member(3, "expoDataFetching", "Provides reliable network request and API data patterns tuned to Expo applications."),
      member(4, "expoNativeUi", "Guides native-feeling screens using platform semantics instead of web-only visual assumptions."),
      member(5, "expoTailwindSetup", "Adds the supported Tailwind setup for consistent universal styling without configuration guesswork."),
      member(6, "expoUpgrade", "Keeps the stack maintainable with official SDK upgrade and dependency repair guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "data-and-ai",
    editorial: {
      title: "Data & AI Systems",
      summary: "A data engineering set spanning Postgres design, serverless databases, Firebase, datasets, and model training.",
      outcome: "Design dependable application data layers and carry curated datasets into reproducible model-training workflows.",
      audience: ["Data engineers", "AI engineers", "Backend product teams"],
      category: "data-ai",
      tags: ["postgres", "firebase", "datasets", "model-training"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "database", colorToken: "blue" },
    },
    members: [
      member(1, "supabasePostgresBestPractices", "Adds Supabase-authored Postgres performance, schema, and operational best practices."),
      member(2, "neonPostgres", "Provides first-party Neon workflows for serverless Postgres development and platform operations."),
      member(3, "firebaseDataConnectBasics", "Uses the current Firebase Data Connect skill for typed application data integration."),
      member(4, "firebaseAiLogicBasics", "Adds official Firebase AI Logic guidance for safely connecting model capabilities to applications."),
      member(5, "huggingfaceDatasets", "Covers dataset creation, transformation, and publication in the Hugging Face ecosystem."),
      member(6, "huggingfaceLlmTrainer", "Extends the workflow into reproducible language-model training with first-party tooling guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "agent-engineering",
    editorial: {
      title: "Agent Engineering",
      summary: "A systems toolkit for skill design, MCP integrations, durable agents, sandboxing, state, and browser control.",
      outcome: "Build capable agent products with explicit tool contracts, state boundaries, safe execution, and browser reach.",
      audience: ["Agent engineers", "AI platform teams", "Tooling developers"],
      category: "agent-engineering",
      tags: ["agents", "mcp", "durable-objects", "sandboxing"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "network", colorToken: "cyan" },
    },
    members: [
      member(1, "anthropicSkillCreator", "Defines a first-party workflow for designing, validating, and maintaining effective Agent Skills."),
      member(2, "anthropicMcpBuilder", "Adds a rigorous first-party path for exposing external capabilities through MCP servers."),
      member(3, "agentsSdk", "Covers Cloudflare's stateful Agents SDK for real-time and long-running agent workloads."),
      member(4, "durableObjects", "Provides the state and coordination primitive needed by durable multi-user agent systems."),
      member(5, "sandboxSdk", "Adds a secure execution boundary for agents that run generated code or untrusted workloads."),
      member(6, "agentBrowser", "Gives agents a maintained browser automation surface for testing and web interaction workflows."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "testing-and-quality",
    editorial: {
      title: "Testing & Quality Loop",
      summary: "A verification stack for browser testing, test-first changes, systematic debugging, reviews, and performance.",
      outcome: "Turn implementation into an evidence-backed delivery loop that catches regressions before declaring work complete.",
      audience: ["Software engineers", "Quality engineers", "Technical leads"],
      category: "testing-quality",
      tags: ["testing", "playwright", "debugging", "performance"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "check-circle", colorToken: "lime" },
    },
    members: [
      member(1, "playwrightCli", "Provides Microsoft's supported CLI workflow for repeatable browser automation and inspection."),
      member(2, "anthropicWebappTesting", "Adds a focused browser-based web application testing workflow with skill-local license evidence."),
      member(3, "testDrivenDevelopment", "Makes executable tests the starting boundary for behavior changes and regressions."),
      member(4, "systematicDebugging", "Introduces a disciplined diagnosis loop before fixes are proposed or implemented."),
      member(5, "verificationBeforeCompletion", "Requires fresh evidence before implementation work is represented as complete."),
      member(6, "requestingCodeReview", "Builds a clear review handoff into the package's delivery workflow."),
      member(7, "webPerf", "Completes quality checks with measured Core Web Vitals and browser performance diagnostics."),
    ],
  },
] as const;

export const launchPackageBlueprints: ReadonlyArray<PackageBlueprint> = Object.freeze(
  blueprintInputs.map((blueprint) => parsePackageBlueprint(blueprint)),
);

export function getLaunchPackageBlueprint(slug: string): PackageBlueprint | undefined {
  return launchPackageBlueprints.find((blueprint) => blueprint.slug === slug);
}
