import {
  parsePackageBlueprint,
  type PackageBlueprint,
  type PackageBlueprintMember,
} from "./package-blueprint";

const observedAt = "2026-07-21";
const refreshedObservedAt = "2026-07-22";

type SourceEvidence = Omit<PackageBlueprintMember, "position" | "defaultSelected" | "rationale">;

const sources = {
  developerKitReactPatterns: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "giuseppe-trisciuoglio",
      repository: "developer-kit",
      repositoryUrl: "https://github.com/giuseppe-trisciuoglio/developer-kit",
      skillPath: "plugins/developer-kit-typescript/skills/react-patterns/SKILL.md",
      upstreamSkillName: "react-patterns",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "306f428f278d83722afdea44a7398dc46dab967f",
      observedAt,
    },
  },
  developerKitTailwindCssPatterns: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "giuseppe-trisciuoglio",
      repository: "developer-kit",
      repositoryUrl: "https://github.com/giuseppe-trisciuoglio/developer-kit",
      skillPath: "plugins/developer-kit-typescript/skills/tailwind-css-patterns/SKILL.md",
      upstreamSkillName: "tailwind-css-patterns",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "306f428f278d83722afdea44a7398dc46dab967f",
      observedAt,
    },
  },
  shadcn: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "shadcn-ui",
      repository: "ui",
      repositoryUrl: "https://github.com/shadcn-ui/ui",
      skillPath: "skills/shadcn/SKILL.md",
      upstreamSkillName: "shadcn",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE.md",
    },
    observedSource: {
      headSha: "fa4872c8ed948c111884e52ae23a649e83591b71",
      observedAt: refreshedObservedAt,
    },
  },
  anthropicFrontendDesign: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/frontend-design/SKILL.md",
      upstreamSkillName: "frontend-design",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/frontend-design/LICENSE.txt",
    },
    observedSource: {
      headSha: "9d2f1ae187231d8199c64b5b762e1bdf2244733d",
      observedAt: refreshedObservedAt,
    },
  },
  impeccable: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "pbakaus",
      repository: "impeccable",
      repositoryUrl: "https://github.com/pbakaus/impeccable",
      skillPath: ".agents/skills/impeccable/SKILL.md",
      upstreamSkillName: "impeccable",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "51b470f903045dc6d459ddfaf6f1700d6a3516e2",
      observedAt,
    },
  },
  gsapScrolltrigger: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/gsap-scrolltrigger/SKILL.md",
      upstreamSkillName: "gsap-scrolltrigger",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  threejsWebgl: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/threejs-webgl/SKILL.md",
      upstreamSkillName: "threejs-webgl",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  reactThreeFiber: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/react-three-fiber/SKILL.md",
      upstreamSkillName: "react-three-fiber",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  motionFramer: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/motion-framer/SKILL.md",
      upstreamSkillName: "motion-framer",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  web3dIntegrationPatterns: {
    publisherClass: "community",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "freshtechbro",
      repository: "claudedesignskills",
      repositoryUrl: "https://github.com/freshtechbro/claudedesignskills",
      skillPath: ".claude/skills/web3d-integration-patterns/SKILL.md",
      upstreamSkillName: "web3d-integration-patterns",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "1da73febff0c3e1dfefc07f8a5ef8f7d1dfdb6cd",
      observedAt,
    },
  },
  hyperframesAnimation: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "heygen-com",
      repository: "hyperframes",
      repositoryUrl: "https://github.com/heygen-com/hyperframes",
      skillPath: "skills/hyperframes-animation/SKILL.md",
      upstreamSkillName: "hyperframes-animation",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "32c41ea7dca14cfa6aa781335ccdd7870e52ceb4",
      observedAt,
    },
  },
  wrangler: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/wrangler/SKILL.md",
      upstreamSkillName: "wrangler",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  workersBestPractices: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/workers-best-practices/SKILL.md",
      upstreamSkillName: "workers-best-practices",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  azureDeploy: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "azure-skills",
      repositoryUrl: "https://github.com/microsoft/azure-skills",
      skillPath: "skills/azure-deploy/SKILL.md",
      upstreamSkillName: "azure-deploy",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "skills/azure-deploy/SKILL.md",
    },
    observedSource: {
      headSha: "1b592c63641049ff33e4952c4021c63b4507f147",
      observedAt: refreshedObservedAt,
    },
  },
  easHosting: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/eas-hosting/SKILL.md",
      upstreamSkillName: "eas-hosting",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/eas-hosting/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  easAppStores: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/eas-app-stores/SKILL.md",
      upstreamSkillName: "eas-app-stores",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/eas-app-stores/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  securityAudit: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "security-audit-skill",
      repositoryUrl: "https://github.com/cloudflare/security-audit-skill",
      skillPath: "skills/security-audit/SKILL.md",
      upstreamSkillName: "security-audit",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "8bac42001ddd90a4dcd8d5a5045199283a8eba75",
      observedAt: refreshedObservedAt,
    },
  },
  firebaseSecurityRulesAuditor: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-security-rules-auditor/SKILL.md",
      upstreamSkillName: "firebase-security-rules-auditor",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt: refreshedObservedAt,
    },
  },
  azureCompliance: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "azure-skills",
      repositoryUrl: "https://github.com/microsoft/azure-skills",
      skillPath: "skills/azure-compliance/SKILL.md",
      upstreamSkillName: "azure-compliance",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "skills/azure-compliance/SKILL.md",
    },
    observedSource: {
      headSha: "1b592c63641049ff33e4952c4021c63b4507f147",
      observedAt: refreshedObservedAt,
    },
  },
  turnstileSpin: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/turnstile-spin/SKILL.md",
      upstreamSkillName: "turnstile-spin",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  cloudflareOne: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/cloudflare-one/SKILL.md",
      upstreamSkillName: "cloudflare-one",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  expoProjectStructure: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-project-structure/SKILL.md",
      upstreamSkillName: "expo-project-structure",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-project-structure/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  expoRouter: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-router/SKILL.md",
      upstreamSkillName: "expo-router",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-router/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  expoDataFetching: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-data-fetching/SKILL.md",
      upstreamSkillName: "expo-data-fetching",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-data-fetching/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  expoNativeUi: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-native-ui/SKILL.md",
      upstreamSkillName: "expo-native-ui",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-native-ui/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  expoTailwindSetup: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-tailwind-setup/SKILL.md",
      upstreamSkillName: "expo-tailwind-setup",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-tailwind-setup/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  expoUpgrade: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "expo",
      repository: "skills",
      repositoryUrl: "https://github.com/expo/skills",
      skillPath: "plugins/expo/skills/expo-upgrade/SKILL.md",
      upstreamSkillName: "expo-upgrade",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "plugins/expo/skills/expo-upgrade/SKILL.md",
    },
    observedSource: {
      headSha: "25e2b5dc24a621ad520596a94c0660d7d4f8bac3",
      observedAt: refreshedObservedAt,
    },
  },
  supabasePostgresBestPractices: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "supabase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/supabase/agent-skills",
      skillPath: "skills/supabase-postgres-best-practices/SKILL.md",
      upstreamSkillName: "supabase-postgres-best-practices",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "skill-frontmatter",
      evidencePath: "skills/supabase-postgres-best-practices/SKILL.md",
    },
    observedSource: {
      headSha: "1ad9aaeb49caafd9e95c0a91116f71890eebbc53",
      observedAt: refreshedObservedAt,
    },
  },
  neonPostgres: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "neondatabase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/neondatabase/agent-skills",
      skillPath: "skills/neon-postgres/SKILL.md",
      upstreamSkillName: "neon-postgres",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d232c83a87bd61bacb1ad60de128fcc91a9b6418",
      observedAt,
    },
  },
  firebaseFirestore: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-firestore/SKILL.md",
      upstreamSkillName: "firebase-firestore",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt: refreshedObservedAt,
    },
  },
  firebaseAiLogicBasics: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "firebase",
      repository: "agent-skills",
      repositoryUrl: "https://github.com/firebase/agent-skills",
      skillPath: "skills/firebase-ai-logic-basics/SKILL.md",
      upstreamSkillName: "firebase-ai-logic-basics",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "538130c39402a40d9c2586ede87def5914641a33",
      observedAt: refreshedObservedAt,
    },
  },
  huggingfaceDatasets: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "huggingface",
      repository: "skills",
      repositoryUrl: "https://github.com/huggingface/skills",
      skillPath: "skills/huggingface-datasets/SKILL.md",
      upstreamSkillName: "huggingface-datasets",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "86cdeee824b73e504198b6005bb113552cdfa7ba",
      observedAt: refreshedObservedAt,
    },
  },
  huggingfaceLlmTrainer: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "huggingface",
      repository: "skills",
      repositoryUrl: "https://github.com/huggingface/skills",
      skillPath: "skills/huggingface-llm-trainer/SKILL.md",
      upstreamSkillName: "huggingface-llm-trainer",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "86cdeee824b73e504198b6005bb113552cdfa7ba",
      observedAt: refreshedObservedAt,
    },
  },
  anthropicSkillCreator: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/skill-creator/SKILL.md",
      upstreamSkillName: "skill-creator",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/skill-creator/LICENSE.txt",
    },
    observedSource: {
      headSha: "9d2f1ae187231d8199c64b5b762e1bdf2244733d",
      observedAt: refreshedObservedAt,
    },
  },
  anthropicMcpBuilder: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/mcp-builder/SKILL.md",
      upstreamSkillName: "mcp-builder",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/mcp-builder/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  agentsSdk: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/agents-sdk/SKILL.md",
      upstreamSkillName: "agents-sdk",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  durableObjects: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/durable-objects/SKILL.md",
      upstreamSkillName: "durable-objects",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  sandboxSdk: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/sandbox-sdk/SKILL.md",
      upstreamSkillName: "sandbox-sdk",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
  agentBrowser: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "vercel-labs",
      repository: "agent-browser",
      repositoryUrl: "https://github.com/vercel-labs/agent-browser",
      skillPath: "skills/agent-browser/SKILL.md",
      upstreamSkillName: "agent-browser",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "81c336c1c20b80ac648e0416a7b6e0c0ae7878bb",
      observedAt: refreshedObservedAt,
    },
  },
  playwrightCli: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "microsoft",
      repository: "playwright-cli",
      repositoryUrl: "https://github.com/microsoft/playwright-cli",
      skillPath: "skills/playwright-cli/SKILL.md",
      upstreamSkillName: "playwright-cli",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "eee5a185c98e6b04d88f580d45a854e9692ab50b",
      observedAt: refreshedObservedAt,
    },
  },
  anthropicWebappTesting: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "anthropics",
      repository: "skills",
      repositoryUrl: "https://github.com/anthropics/skills",
      skillPath: "skills/webapp-testing/SKILL.md",
      upstreamSkillName: "webapp-testing",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "skill-local-license",
      evidencePath: "skills/webapp-testing/LICENSE.txt",
    },
    observedSource: {
      headSha: "fa0fa64bdc967915dc8399e803be67759e1e62b8",
      observedAt,
    },
  },
  testDrivenDevelopment: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/test-driven-development/SKILL.md",
      upstreamSkillName: "test-driven-development",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt: refreshedObservedAt,
    },
  },
  systematicDebugging: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/systematic-debugging/SKILL.md",
      upstreamSkillName: "systematic-debugging",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt: refreshedObservedAt,
    },
  },
  verificationBeforeCompletion: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/verification-before-completion/SKILL.md",
      upstreamSkillName: "verification-before-completion",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt: refreshedObservedAt,
    },
  },
  requestingCodeReview: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "obra",
      repository: "superpowers",
      repositoryUrl: "https://github.com/obra/superpowers",
      skillPath: "skills/requesting-code-review/SKILL.md",
      upstreamSkillName: "requesting-code-review",
    },
    observedLicense: {
      spdx: "MIT",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "d884ae04edebef577e82ff7c4e143debd0bbec99",
      observedAt: refreshedObservedAt,
    },
  },
  webPerf: {
    publisherClass: "official",
    locator: {
      kind: "public-github-skill-locator",
      host: "github.com",
      visibility: "public",
      owner: "cloudflare",
      repository: "skills",
      repositoryUrl: "https://github.com/cloudflare/skills",
      skillPath: "skills/web-perf/SKILL.md",
      upstreamSkillName: "web-perf",
    },
    observedLicense: {
      spdx: "Apache-2.0",
      evidenceClass: "repository-license",
      evidencePath: "LICENSE",
    },
    observedSource: {
      headSha: "70215303d44a81a0db3219428f4825b604fc6061",
      observedAt: refreshedObservedAt,
    },
  },
} as const satisfies Record<string, SourceEvidence>;

type SourceKey = keyof typeof sources;

function member(position: number, source: SourceKey, rationale: string): PackageBlueprintMember {
  return {
    position,
    defaultSelected: true,
    rationale,
    ...sources[source],
  };
}

const blueprintInputs = [
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "frontend-foundations",
    editorial: {
      title: "Frontend Foundations",
      summary: "A disciplined React interface stack spanning architecture, responsive styling, and accessible components.",
      outcome: "Ship maintainable, fast product interfaces with stronger composition and a coherent component foundation.",
      audience: ["Frontend engineers", "Product engineers", "Design engineers"],
      category: "frontend",
      tags: ["react", "nextjs", "components", "ui-design"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "brackets", colorToken: "iris" },
    },
    members: [
      member(1, "developerKitReactPatterns", "Adds current React 19 patterns for concurrent rendering, optimistic interfaces, Server Actions, and performance."),
      member(2, "developerKitTailwindCssPatterns", "Provides responsive Tailwind CSS patterns for accessible components, layouts, and maintainable design systems."),
      member(3, "shadcn", "Brings first-party shadcn guidance for selecting, integrating, and adapting accessible UI components."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "motion-and-3d",
    editorial: {
      title: "Motion & 3D",
      summary: "A community-led motion toolkit for scroll choreography, WebGL scenes, React 3D, and cinematic timelines.",
      outcome: "Build expressive, performant web experiences while choosing the right animation and 3D abstraction for each scene.",
      audience: ["Creative developers", "Design engineers", "Interactive studios"],
      category: "motion-3d",
      tags: ["gsap", "threejs", "webgl", "animation"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "orbit", colorToken: "magenta" },
    },
    members: [
      member(1, "gsapScrolltrigger", "Covers practical GSAP ScrollTrigger choreography for scroll-driven product and editorial sequences."),
      member(2, "threejsWebgl", "Supplies direct Three.js and WebGL patterns when scene-level control matters more than abstraction."),
      member(3, "reactThreeFiber", "Connects declarative React workflows to Three.js for componentized interactive scenes."),
      member(4, "motionFramer", "Adds focused Motion guidance for interface transitions, gestures, and layout animation."),
      member(5, "web3dIntegrationPatterns", "Explains how the included motion and 3D tools work together in one coherent application architecture."),
      member(6, "hyperframesAnimation", "Adds an Apache-licensed, author-maintained animation system for structured cinematic timelines."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "deployment",
    editorial: {
      title: "Deployment Control Plane",
      summary: "A practical release stack across Cloudflare, Expo hosting, and mobile store delivery.",
      outcome: "Move applications from local builds to production infrastructure with platform-specific operational guidance.",
      audience: ["Platform engineers", "Full-stack teams", "Mobile release owners"],
      category: "deployment",
      tags: ["cloudflare", "azure", "expo", "release"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "rocket", colorToken: "amber" },
    },
    members: [
      member(1, "wrangler", "Provides first-party Wrangler commands and workflows for Cloudflare development and deployment."),
      member(2, "workersBestPractices", "Adds production-focused Workers architecture and review guidance before a release reaches users."),
      member(3, "easHosting", "Handles Expo web exports and Router API deployments through the supported EAS hosting workflow."),
      member(4, "easAppStores", "Completes the mobile release path with official EAS build and app-store submission guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "cybersecurity",
    editorial: {
      title: "Security Surface",
      summary: "A defensive review kit for application code, cloud posture, identity boundaries, and security rules.",
      outcome: "Catch common security weaknesses earlier and apply provider-specific controls with explicit scope and provenance.",
      audience: ["Security engineers", "Platform teams", "Application maintainers"],
      category: "cybersecurity",
      tags: ["security", "compliance", "zero-trust", "appsec"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "shield", colorToken: "emerald" },
    },
    members: [
      member(1, "securityAudit", "Provides Cloudflare's dedicated application security audit workflow for structured defensive reviews."),
      member(2, "firebaseSecurityRulesAuditor", "Checks Firebase rules with first-party product context that generic security guidance cannot supply."),
      member(3, "azureCompliance", "Adds Microsoft-authored Azure compliance assessment and remediation guidance."),
      member(4, "cloudflareOne", "Expands the package to Zero Trust access, network, data, and device policy boundaries."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "mobile",
    editorial: {
      title: "Expo Mobile Workshop",
      summary: "An official Expo foundation for project structure, routing, data, native UI, styling, and upgrades.",
      outcome: "Build and maintain production Expo applications with coherent conventions across the full development lifecycle.",
      audience: ["React Native engineers", "Expo teams", "Web-to-mobile developers"],
      category: "mobile",
      tags: ["expo", "react-native", "routing", "native-ui"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "device-mobile", colorToken: "coral" },
    },
    members: [
      member(1, "expoProjectStructure", "Establishes a durable first-party folder and project structure before application complexity grows."),
      member(2, "expoRouter", "Covers the official routing model, file conventions, layouts, groups, and navigation boundaries."),
      member(3, "expoDataFetching", "Provides reliable network request and API data patterns tuned to Expo applications."),
      member(4, "expoNativeUi", "Guides native-feeling screens using platform semantics instead of web-only visual assumptions."),
      member(5, "expoTailwindSetup", "Adds the supported Tailwind setup for consistent universal styling without configuration guesswork."),
      member(6, "expoUpgrade", "Keeps the stack maintainable with official SDK upgrade and dependency repair guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "data-and-ai",
    editorial: {
      title: "Data & AI Systems",
      summary: "A data engineering set spanning Postgres design, Firebase, datasets, and model training.",
      outcome: "Design dependable application data layers and carry curated datasets into reproducible model-training workflows.",
      audience: ["Data engineers", "AI engineers", "Backend product teams"],
      category: "data-ai",
      tags: ["postgres", "firebase", "datasets", "model-training"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "database", colorToken: "blue" },
    },
    members: [
      member(1, "supabasePostgresBestPractices", "Adds Supabase-authored Postgres performance, schema, and operational best practices."),
      member(2, "firebaseFirestore", "Adds first-party Firestore guidance for modeling, querying, and securing Firebase application data."),
      member(3, "firebaseAiLogicBasics", "Adds official Firebase AI Logic guidance for safely connecting model capabilities to applications."),
      member(4, "huggingfaceDatasets", "Covers dataset creation, transformation, and publication in the Hugging Face ecosystem."),
      member(5, "huggingfaceLlmTrainer", "Extends the workflow into reproducible language-model training with first-party tooling guidance."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "agent-engineering",
    editorial: {
      title: "Agent Engineering",
      summary: "A systems toolkit for durable agents, sandboxed execution, state, and browser control.",
      outcome: "Build capable agent products with explicit tool contracts, state boundaries, safe execution, and browser reach.",
      audience: ["Agent engineers", "AI platform teams", "Tooling developers"],
      category: "agent-engineering",
      tags: ["agents", "mcp", "durable-objects", "sandboxing"],
      featured: true,
      reviewedAt: observedAt,
      visual: { iconToken: "network", colorToken: "cyan" },
    },
    members: [
      member(1, "agentsSdk", "Covers Cloudflare's stateful Agents SDK for real-time and long-running agent workloads."),
      member(2, "durableObjects", "Provides the state and coordination primitive needed by durable multi-user agent systems."),
      member(3, "sandboxSdk", "Adds a secure execution boundary for agents that run generated code or untrusted workloads."),
      member(4, "agentBrowser", "Gives agents a maintained browser automation surface for testing and web interaction workflows."),
    ],
  },
  {
    schemaVersion: 1,
    kind: "editorial-package-blueprint",
    slug: "testing-and-quality",
    editorial: {
      title: "Testing & Quality Loop",
      summary: "A verification stack for browser testing, test-first changes, systematic debugging, reviews, and performance.",
      outcome: "Turn implementation into an evidence-backed delivery loop that catches regressions before declaring work complete.",
      audience: ["Software engineers", "Quality engineers", "Technical leads"],
      category: "testing-quality",
      tags: ["testing", "playwright", "debugging", "performance"],
      featured: false,
      reviewedAt: observedAt,
      visual: { iconToken: "check-circle", colorToken: "lime" },
    },
    members: [
      member(1, "playwrightCli", "Provides Microsoft's supported CLI workflow for repeatable browser automation and inspection."),
      member(2, "testDrivenDevelopment", "Makes executable tests the starting boundary for behavior changes and regressions."),
      member(3, "systematicDebugging", "Introduces a disciplined diagnosis loop before fixes are proposed or implemented."),
      member(4, "verificationBeforeCompletion", "Requires fresh evidence before implementation work is represented as complete."),
      member(5, "requestingCodeReview", "Builds a clear review handoff into the package's delivery workflow."),
      member(6, "webPerf", "Completes quality checks with measured Core Web Vitals and browser performance diagnostics."),
    ],
  },
] as const;

export const launchPackageBlueprints: ReadonlyArray<PackageBlueprint> = Object.freeze(
  blueprintInputs.map((blueprint) => parsePackageBlueprint(blueprint)),
);

/** Public upstream repositories required to resolve every launch blueprint. */
export const launchPackageRepositoryUrls: readonly string[] = Object.freeze(
  [...new Set(
    launchPackageBlueprints.flatMap((blueprint) =>
      blueprint.members.map((member) => member.locator.repositoryUrl),
    ),
  )].sort(),
);

if (launchPackageRepositoryUrls.length !== 14) {
  throw new Error(
    `Launch package repository inventory changed: expected 14 public origins, found ${launchPackageRepositoryUrls.length}.`,
  );
}

export function getLaunchPackageBlueprint(slug: string): PackageBlueprint | undefined {
  return launchPackageBlueprints.find((blueprint) => blueprint.slug === slug);
}
